import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedIonchevronbackcircleWidget51.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedAnubhav1Widget3.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedCFP1Widget3.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedPostDoc1Widget3.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedGM1Widget3.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedIonchevronbackcircleWidget53.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedIonchevronbackcircleWidget49.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedAnubhavFellowshipWidget3.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedCallForProposalWidget3.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedPostDoctoralFellowshipWidget3.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedIonchevronbackcircleWidget50.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedIonchevronbackcircleWidget52.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedIonchevronbackcircleWidget48.dart';
import 'package:flutterapp/untilapp/generatedframe23widget4/generated/GeneratedRecruitmentWidget7.dart';

/* Frame Frame 23
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame23Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 1696.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 1696.0,
                      height: 550.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 1321.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 508.0,
                              child: GeneratedCFP1Widget3(),
                            ),
                            Positioned(
                              left: 868.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 199.0,
                              child: GeneratedAnubhav1Widget3(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 122.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 198.0,
                              child: GeneratedPostDoc1Widget3(),
                            ),
                            Positioned(
                              left: 175.0,
                              top: 358.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 31.0,
                              child: GeneratedRecruitmentWidget7(),
                            ),
                            Positioned(
                              left: 561.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedPostDoctoralFellowshipWidget3(),
                            ),
                            Positioned(
                              left: 998.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedAnubhavFellowshipWidget3(),
                            ),
                            Positioned(
                              left: 1464.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedCallForProposalWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 227.0,
                              child: GeneratedGM1Widget3(),
                            ),
                            Positioned(
                              left: 1325.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget48(),
                            ),
                            Positioned(
                              left: 865.0,
                              top: 201.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget49(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 188.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget50(),
                            ),
                            Positioned(
                              left: 400.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget51(),
                            ),
                            Positioned(
                              left: 816.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget52(),
                            ),
                            Positioned(
                              left: 1243.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget53(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
