import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedGM1Widget4.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedPostDoc1Widget4.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedRecruitmentWidget8.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedIonchevronbackcircleWidget58.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedPostDoctoralFellowshipWidget4.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedIonchevronbackcircleWidget56.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedIonchevronbackcircleWidget59.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedIonchevronbackcircleWidget57.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedAnubhav1Widget4.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedIonchevronbackcircleWidget54.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedCallForProposalWidget4.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedAnubhavFellowshipWidget4.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedIonchevronbackcircleWidget55.dart';
import 'package:flutterapp/untilapp/generatedframe24widget1/generated/GeneratedCFP1Widget4.dart';

/* Frame Frame 24
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame24Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 1696.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 1696.0,
                      height: 550.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 1321.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 508.0,
                              child: GeneratedCFP1Widget4(),
                            ),
                            Positioned(
                              left: 868.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 199.0,
                              child: GeneratedAnubhav1Widget4(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 122.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 198.0,
                              child: GeneratedPostDoc1Widget4(),
                            ),
                            Positioned(
                              left: 175.0,
                              top: 358.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 31.0,
                              child: GeneratedRecruitmentWidget8(),
                            ),
                            Positioned(
                              left: 561.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedPostDoctoralFellowshipWidget4(),
                            ),
                            Positioned(
                              left: 998.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedAnubhavFellowshipWidget4(),
                            ),
                            Positioned(
                              left: 1464.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedCallForProposalWidget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 227.0,
                              child: GeneratedGM1Widget4(),
                            ),
                            Positioned(
                              left: 1325.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget54(),
                            ),
                            Positioned(
                              left: 835.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget55(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 188.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget56(),
                            ),
                            Positioned(
                              left: 400.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget57(),
                            ),
                            Positioned(
                              left: 816.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget58(),
                            ),
                            Positioned(
                              left: 1243.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget59(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
