import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget416 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 29.918697357177734,
      height: 15.308330535888672,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.23532 5.7L12.027 14.3333C13.652 15.6333 16.277 15.6333 17.902 14.3333L28.6936 5.7C31.3186 3.6 29.4436 0 25.7353 0L4.15199 0C0.443654 0 -1.38968 3.6 1.23532 5.7Z')
          ..color = Color.fromARGB(255, 168, 128, 128),
      ]),
    ));
  }
}
