import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget73.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedDetailshttpsiitmandiacinacademicsfilespost20doc20fellow4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedRectangle1Widget25.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedCFP1Widget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedAboutUsWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedFeedbackWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedAnubhav1Widget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedCallForProposalsWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedFacultyFellowshipProgramWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedGM1Widget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedPostDoctoralFellowshipWidget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedDetailshttpsiitmandiacinacademicsfilesAnubhav20Fellowsh4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedTeamWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget76.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget75.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedHttpsiitmandiacinadministrationadvrtproposal_AI_ML_Dec24.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedCallForProposalWidget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedContactUsWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedCFPWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedRectangle29Widget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedDetailshttpsiitmandiacinadministrationadvrtihub_faculty4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedAnubhavFellowshipProgramWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedIITmandi1Widget25.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedPostDoc1Widget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedRecruitmentWidget11.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedDetailshttpsiitmandiacinadministrationadvrtadvt_GM_tih_4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget72.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedNMICPSWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedGeneralProjectManagerApplicationsareinvitedforthepostof4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget74.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedProjectsWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedHomeWidget14.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedAnubhavFellowshipWidget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedCarbonoverflowmenuverticalWidget21.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget77.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedRecruitmentWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedAkariconscirclechevronleftfillWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox47widget/generated/GeneratedPostDoctoralFellowshipsWidget4.dart';

/* Frame iPhone 11 Pro / X - 47
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX47Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 123.0,
                top: 158.0,
                right: 108.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedRecruitmentWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget25(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget25(),
              ),
              Positioned(
                left: null,
                top: 52.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget21(),
              ),
              Positioned(
                left: 34.0,
                top: 1027.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedFacultyFellowshipProgramWidget4(),
              ),
              Positioned(
                left: 43.0,
                top: 1114.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedPostDoctoralFellowshipsWidget4(),
              ),
              Positioned(
                left: 39.0,
                top: 1061.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedDetailshttpsiitmandiacinadministrationadvrtihub_faculty4(),
              ),
              Positioned(
                left: 34.0,
                top: 773.0,
                right: 26.0,
                bottom: null,
                width: null,
                height: 67.0,
                child:
                    GeneratedGeneralProjectManagerApplicationsareinvitedforthepostof4(),
              ),
              Positioned(
                left: 34.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 59.0,
                child:
                    GeneratedDetailshttpsiitmandiacinadministrationadvrtadvt_GM_tih_4(),
              ),
              Positioned(
                left: 88.0,
                top: 941.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 40.0,
                child: GeneratedProjectsWidget4(),
              ),
              Positioned(
                left: 44.0,
                top: 1143.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedDetailshttpsiitmandiacinacademicsfilespost20doc20fellow4(),
              ),
              Positioned(
                left: 47.0,
                top: 1196.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedAnubhavFellowshipProgramWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 1228.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedDetailshttpsiitmandiacinacademicsfilesAnubhav20Fellowsh4(),
              ),
              Positioned(
                left: 128.0,
                top: 1306.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 40.0,
                child: GeneratedCFPWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 1366.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedCallForProposalsWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 1393.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 55.0,
                child:
                    GeneratedHttpsiitmandiacinadministrationadvrtproposal_AI_ML_Dec24(),
              ),
              Positioned(
                left: 1296.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 508.0,
                child: GeneratedCFP1Widget7(),
              ),
              Positioned(
                left: 843.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 199.0,
                child: GeneratedAnubhav1Widget7(),
              ),
              Positioned(
                left: 416.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 198.0,
                child: GeneratedPostDoc1Widget7(),
              ),
              Positioned(
                left: 150.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 31.0,
                child: GeneratedRecruitmentWidget12(),
              ),
              Positioned(
                left: 536.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 28.0,
                child: GeneratedPostDoctoralFellowshipWidget7(),
              ),
              Positioned(
                left: 973.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 28.0,
                child: GeneratedAnubhavFellowshipWidget7(),
              ),
              Positioned(
                left: 1439.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 28.0,
                child: GeneratedCallForProposalWidget7(),
              ),
              Positioned(
                left: -25.0,
                top: 225.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 227.0,
                child: GeneratedGM1Widget7(),
              ),
              Positioned(
                left: 1300.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget72(),
              ),
              Positioned(
                left: 810.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget73(),
              ),
              Positioned(
                left: 416.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget74(),
              ),
              Positioned(
                left: 375.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget75(),
              ),
              Positioned(
                left: 791.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget76(),
              ),
              Positioned(
                left: 1218.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget77(),
              ),
              Positioned(
                left: 0.0,
                top: 107.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 702.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6213333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle29Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 139.0,
                right: 160.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedAkariconscirclechevronleftfillWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 228.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.19466666666666665;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.20266666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedHomeWidget14(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 276.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 25.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2773333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16266666666666665,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedAboutUsWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 321.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18133333333333335,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedNMICPSWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 372.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 25.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3333333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16266666666666665,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedContactUsWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 422.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.30133333333333334;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18133333333333335,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFeedbackWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 464.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18133333333333335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23466666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedTeamWidget5(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
