import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedCarbonoverflowmenuverticalWidget9.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedFordetailshttpswwwiitmandicatalystinactivestartupsporte1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedIITmandi1Widget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedSinceourestablishmentatIITMandiwehavehandpickedinnovati1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedHomeWidget11.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedRectangle29Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedRectangle1Widget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedAkariconscirclechevronleftfillWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedStartupsWidget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedAboutUsWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedFeedbackWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedStartup1Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedContactUsWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedTeamWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox46widget/generated/GeneratedNMICPSWidget2.dart';

/* Frame iPhone 11 Pro / X - 46
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX46Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 141.0,
                top: 130.0,
                right: 132.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedStartupsWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget10(),
              ),
              Positioned(
                left: 24.0,
                top: 557.0,
                right: 36.0,
                bottom: null,
                width: null,
                height: 288.0,
                child:
                    GeneratedSinceourestablishmentatIITMandiwehavehandpickedinnovati1(),
              ),
              Positioned(
                left: 30.0,
                top: 706.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 28.0,
                child:
                    GeneratedFordetailshttpswwwiitmandicatalystinactivestartupsporte1(),
              ),
              Positioned(
                left: null,
                top: 52.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 172.0,
                right: -4.0,
                bottom: null,
                width: null,
                height: 232.0,
                child: GeneratedStartup1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 107.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 705.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6213333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle29Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 139.0,
                right: 160.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedAkariconscirclechevronleftfillWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 228.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.19466666666666665;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.20266666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedHomeWidget11(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 276.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 25.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2773333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16266666666666665,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedAboutUsWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 321.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18133333333333335,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedNMICPSWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 372.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 25.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3333333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16266666666666665,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedContactUsWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 422.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.30133333333333334;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18133333333333335,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFeedbackWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 464.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18133333333333335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23466666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedTeamWidget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
