import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedGiveusyourfeedbackhereWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedMonishaBahugunaWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/Generated919015458338Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedImage4Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedCarbonoverflowmenuverticalWidget24.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedBrandicoinstagramfilledWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedMobasherahFalakWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedIITmandi1Widget30.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedTeamWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedImage5Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedContactWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedAssociatePROutreachWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedEmailceoihubiitmandiinWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedMrAvinashPunekarCEOIITMandiiHubandHCIFoundationWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedImage7Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedRectangle1Widget30.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedAppDevelopersWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedDollyChoudharyWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedBytesizemenuWidget24.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedEmaildollychoudhary220gmailcomWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedFabrandstwittersquareWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedConnectwithusWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedBrandicolinkedinrectWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedEmailmfabasherahgmailcomWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedKooBlackIcon300x300Copy1Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedChiefExecutiveOfficerWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedBrandicofacebookrectWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedEmailmonishaihubiitmandiinWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedFabasherahMalakWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox11widget/generated/GeneratedEmailfmobasherah111gmailcomWidget.dart';

/* Frame iPhone 11 Pro / X - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1526.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 378.0,
                      height: 1526.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 593.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 341.0,
                              child: GeneratedRectangle14Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 112.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0160000109798695;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          -0.015999999626603707,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget30(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 54.0,
                              child: TransformHelper.translate(
                                  x: -4.50,
                                  y: -683.00,
                                  z: 0,
                                  child: GeneratedIITmandi1Widget30()),
                            ),
                            Positioned(
                              left: 24.0,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -683.00,
                                  z: 0,
                                  child: GeneratedBytesizemenuWidget24()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -686.00,
                                  z: 0,
                                  child:
                                      GeneratedCarbonoverflowmenuverticalWidget24()),
                            ),
                            Positioned(
                              left: -3.0239999294281006,
                              top: 1214.0,
                              right: -3.0240042209625244,
                              bottom: null,
                              width: null,
                              height: 312.0,
                              child: GeneratedRectangle2Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 217.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 338.0,
                              child: GeneratedRectangle15Widget(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 233.0,
                              right: 68.0,
                              bottom: null,
                              width: null,
                              height: 16.0,
                              child: GeneratedChiefExecutiveOfficerWidget(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 406.0,
                              right: 68.0,
                              bottom: null,
                              width: null,
                              height: 16.0,
                              child: GeneratedAssociatePROutreachWidget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 598.0,
                              right: 64.0,
                              bottom: null,
                              width: null,
                              height: 23.0,
                              child: GeneratedAppDevelopersWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 278.0,
                              right: 36.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  GeneratedMrAvinashPunekarCEOIITMandiiHubandHCIFoundationWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 484.0,
                              right: 33.0,
                              bottom: null,
                              width: null,
                              height: 38.0,
                              child:
                                  GeneratedEmailmonishaihubiitmandiinWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 466.0,
                              right: 36.0,
                              bottom: null,
                              width: null,
                              height: 16.0,
                              child: GeneratedMonishaBahugunaWidget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 306.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 52.0,
                              child: GeneratedEmailceoihubiitmandiinWidget(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 152.0,
                              right: 149.0,
                              bottom: null,
                              width: null,
                              height: 34.0,
                              child: GeneratedTeamWidget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1008.0,
                              right: 7.0,
                              bottom: null,
                              width: null,
                              height: 25.0,
                              child: GeneratedGiveusyourfeedbackhereWidget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 1233.0,
                              right: 21.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child:
                                  GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 84.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: 115.00,
                                  z: 0,
                                  child: GeneratedImage2Widget()),
                            ),
                            Positioned(
                              left: 141.750732421875,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 77.27371978759766,
                              height: 82.16021728515625,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: 0.08,
                                  z: 0,
                                  child: GeneratedImage3Widget()),
                            ),
                            Positioned(
                              left: null,
                              top: 251.0,
                              right: 33.0,
                              bottom: null,
                              width: 87.0,
                              height: 97.0,
                              child: GeneratedImage5Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: 422.0,
                              right: 39.0,
                              bottom: null,
                              width: 71.0,
                              height: 92.0,
                              child: GeneratedImage7Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 642.0,
                              right: null,
                              bottom: null,
                              width: 83.0,
                              height: 83.0,
                              child: GeneratedImage4Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 61.0,
                              height: 55.0,
                              child: TransformHelper.translate(
                                  x: 138.50,
                                  y: 720.50,
                                  z: 0,
                                  child: GeneratedBrandicolinkedinrectWidget()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 51.0,
                              child: TransformHelper.translate(
                                  x: 64.00,
                                  y: 721.50,
                                  z: 0,
                                  child: GeneratedBrandicofacebookrectWidget()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 55.0,
                              child: TransformHelper.translate(
                                  x: -9.00,
                                  y: 721.50,
                                  z: 0,
                                  child:
                                      GeneratedBrandicoinstagramfilledWidget()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 60.0,
                              child: TransformHelper.translate(
                                  x: -80.50,
                                  y: 721.00,
                                  z: 0,
                                  child:
                                      GeneratedFabrandstwittersquareWidget()),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 1423.0,
                              right: 126.0,
                              bottom: null,
                              width: null,
                              height: 20.0,
                              child: GeneratedConnectwithusWidget(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 1359.0,
                              right: 284.0,
                              bottom: null,
                              width: null,
                              height: 23.0,
                              child: GeneratedContactWidget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 1359.0,
                              right: 154.0,
                              bottom: null,
                              width: null,
                              height: 20.0,
                              child: Generated919015458338Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 56.0,
                              child: TransformHelper.translate(
                                  x: -149.00,
                                  y: 719.00,
                                  z: 0,
                                  child:
                                      GeneratedKooBlackIcon300x300Copy1Widget()),
                            ),
                            Positioned(
                              left: 191.0,
                              top: 672.0,
                              right: -131.0,
                              bottom: null,
                              width: null,
                              height: 16.0,
                              child: GeneratedMobasherahFalakWidget(),
                            ),
                            Positioned(
                              left: 191.0,
                              top: 766.0,
                              right: -131.0,
                              bottom: null,
                              width: null,
                              height: 16.0,
                              child: GeneratedFabasherahMalakWidget(),
                            ),
                            Positioned(
                              left: 191.0,
                              top: 859.0,
                              right: -131.0,
                              bottom: null,
                              width: null,
                              height: 16.0,
                              child: GeneratedDollyChoudharyWidget(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 705.0,
                              right: -138.0,
                              bottom: null,
                              width: null,
                              height: 26.0,
                              child:
                                  GeneratedEmailfmobasherah111gmailcomWidget(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 809.0,
                              right: -130.0,
                              bottom: null,
                              width: null,
                              height: 29.0,
                              child: GeneratedEmailmfabasherahgmailcomWidget(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 885.0,
                              right: -139.0,
                              bottom: null,
                              width: null,
                              height: 26.0,
                              child:
                                  GeneratedEmaildollychoudhary220gmailcomWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
