import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox17widget/generated/GeneratedIcbaselineverifieduserWidget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox17widget/generated/GeneratedOTPVERIFIEDWidget.dart';

/* Frame iPhone 11 Pro / X - 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX17Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedIPhone11ProX5Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(20.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 124.0,
                  top: 341.0,
                  right: null,
                  bottom: null,
                  width: 135.0,
                  height: 135.0,
                  child: GeneratedIcbaselineverifieduserWidget(),
                ),
                Positioned(
                  left: 48.0,
                  top: 290.0,
                  right: null,
                  bottom: null,
                  width: 269.0,
                  height: 23.0,
                  child: GeneratedOTPVERIFIEDWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
