import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedBrandicofacebookrectWidget15.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedContactUsWidget11.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedIITmandi1Widget45.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedBrandicoinstagramfilledWidget15.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedKooBlackIcon300x300Copy1Widget15.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedTeamWidget14.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedHomeWidget20.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedContactWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedFabrandstwittersquareWidget15.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedRectangle29Widget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedFeedbackWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedConnectwithusWidget15.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedRectangle15Widget6.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedSubmitWidget3.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedWhydoyouwanttojoinusWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedAkariconscirclechevronleftfillWidget11.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedRectangle2Widget18.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedTihiitmandiacinWidget3.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedBrandicolinkedinrectWidget15.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/Generated919015458338Widget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedNMICPSWidget14.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedAboutUsWidget11.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedWritetousWidget3.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedRectangle1Widget45.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedCarbonoverflowmenuverticalWidget34.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedRectangle2Widget17.dart';
import 'package:flutterapp/untilapp/generatediphone11prox56widget/generated/GeneratedJoinWidget11.dart';

/* Frame iPhone 11 Pro / X - 56
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX56Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget45(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget45(),
              ),
              Positioned(
                left: null,
                top: 52.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget34(),
              ),
              Positioned(
                left: 0.0,
                top: 643.0,
                right: -6.0,
                bottom: null,
                width: null,
                height: 312.0,
                child: GeneratedRectangle2Widget17(),
              ),
              Positioned(
                left: 29.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedWritetousWidget3(),
              ),
              Positioned(
                left: 26.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 22.0,
                child: GeneratedWhydoyouwanttojoinusWidget2(),
              ),
              Positioned(
                left: 102.0,
                top: 219.0,
                right: 170.0,
                bottom: null,
                width: null,
                height: 19.0,
                child: GeneratedTihiitmandiacinWidget3(),
              ),
              Positioned(
                left: 139.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 40.0,
                child: GeneratedJoinWidget11(),
              ),
              Positioned(
                left: 17.0,
                top: 673.0,
                right: 15.0,
                bottom: null,
                width: null,
                height: 92.0,
                child:
                    GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK12(),
              ),
              Positioned(
                left: 16.0,
                top: 297.0,
                right: 49.0,
                bottom: null,
                width: null,
                height: 157.0,
                child: GeneratedRectangle15Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 491.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3253333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.608,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedSubmitWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 485.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 33.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.30666666666666664;
                  double scaleX = (constraints.maxWidth * percentWidth) / 115.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5333333333333333,
                        translateY: 0,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: 1,
                        scaleZ: 1,
                        child: GeneratedRectangle2Widget18())
                  ]);
                }),
              ),
              Positioned(
                left: 297.0,
                top: 885.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 55.0,
                child: GeneratedBrandicolinkedinrectWidget15(),
              ),
              Positioned(
                left: 224.0,
                top: 888.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 51.0,
                child: GeneratedBrandicofacebookrectWidget15(),
              ),
              Positioned(
                left: 156.0,
                top: 886.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 55.0,
                child: GeneratedBrandicoinstagramfilledWidget15(),
              ),
              Positioned(
                left: 84.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 60.0,
                child: GeneratedFabrandstwittersquareWidget15(),
              ),
              Positioned(
                left: 120.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 23.0,
                child: GeneratedConnectwithusWidget15(),
              ),
              Positioned(
                left: 24.0,
                top: 788.0,
                right: 287.0,
                bottom: null,
                width: null,
                height: 23.0,
                child: GeneratedContactWidget12(),
              ),
              Positioned(
                left: 85.0,
                top: 788.0,
                right: 172.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: Generated919015458338Widget12(),
              ),
              Positioned(
                left: 17.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 56.0,
                child: GeneratedKooBlackIcon300x300Copy1Widget15(),
              ),
              Positioned(
                left: -1.0,
                top: 106.0,
                right: 143.0,
                bottom: null,
                width: null,
                height: 706.0,
                child: GeneratedRectangle29Widget5(),
              ),
              Positioned(
                left: null,
                top: 138.0,
                right: 161.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedAkariconscirclechevronleftfillWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 227.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.19466666666666665;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedHomeWidget20(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 275.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 31.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2773333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedAboutUsWidget11(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 320.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.168,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedNMICPSWidget14(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 371.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 31.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3333333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedContactUsWidget11(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 421.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.30133333333333334;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17866666666666667,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFeedbackWidget12(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 463.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18133333333333335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.232,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedTeamWidget14(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
