import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox38widget/generated/GeneratedStartup1Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox38widget/generated/GeneratedStartupsWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox38widget/generated/GeneratedRectangle29Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox38widget/generated/GeneratedIITmandi1Widget11.dart';
import 'package:flutterapp/untilapp/generatediphone11prox38widget/generated/GeneratedRectangle1Widget11.dart';
import 'package:flutterapp/untilapp/generatediphone11prox38widget/generated/GeneratedBytesizemenuWidget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox38widget/generated/GeneratedStartupsWidget11.dart';
import 'package:flutterapp/untilapp/generatediphone11prox38widget/generated/GeneratedFrame28Widget.dart';

/* Frame iPhone 11 Pro / X - 38
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX38Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget11(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget11(),
              ),
              Positioned(
                left: 24.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: GeneratedBytesizemenuWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 479.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 333.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedStartupsWidget11(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 122.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 40.0,
                child: GeneratedStartupsWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 172.0,
                right: -4.0,
                bottom: null,
                width: null,
                height: 232.0,
                child: GeneratedStartup1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 106.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 701.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7573333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.248,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle29Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 694.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.84;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2693333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame28Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
