import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedIITmandi1Widget35.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedBrandicoinstagramfilledWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedCarbonoverflowmenuverticalWidget28.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedContactWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedConnectwithusWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedBrandicofacebookrectWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedFabrandstwittersquareWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedRectangle2Widget6.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedFrame8Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedKooBlackIcon300x300Copy1Widget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedBytesizemenuWidget28.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedBrandicolinkedinrectWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/Generated919015458338Widget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox70widget/generated/GeneratedRectangle1Widget35.dart';

/* Frame iPhone 11 Pro / X - 70
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX70Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 955.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 955.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 112.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.016;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget35(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 155.0,
                              top: 53.0,
                              right: 163.0,
                              bottom: null,
                              width: null,
                              height: 54.0,
                              child: GeneratedIITmandi1Widget35(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -397.50,
                                  z: 0,
                                  child: GeneratedBytesizemenuWidget28()),
                            ),
                            Positioned(
                              left: null,
                              top: 52.0,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child:
                                  GeneratedCarbonoverflowmenuverticalWidget28(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 151.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 804.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.016;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedFrame8Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: -3.02392578125,
                              top: 643.0,
                              right: -6.024078369140625,
                              bottom: null,
                              width: null,
                              height: 312.0,
                              child: GeneratedRectangle2Widget6(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 662.0,
                              right: 18.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child:
                                  GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK5(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 61.0,
                              height: 55.0,
                              child: TransformHelper.translate(
                                  x: 140.00,
                                  y: 435.00,
                                  z: 0,
                                  child:
                                      GeneratedBrandicolinkedinrectWidget5()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 51.0,
                              child: TransformHelper.translate(
                                  x: 65.50,
                                  y: 436.00,
                                  z: 0,
                                  child:
                                      GeneratedBrandicofacebookrectWidget5()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 55.0,
                              child: TransformHelper.translate(
                                  x: -7.50,
                                  y: 436.00,
                                  z: 0,
                                  child:
                                      GeneratedBrandicoinstagramfilledWidget5()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 60.0,
                              child: TransformHelper.translate(
                                  x: -79.00,
                                  y: 435.50,
                                  z: 0,
                                  child:
                                      GeneratedFabrandstwittersquareWidget5()),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 852.0,
                              right: 123.0,
                              bottom: null,
                              width: null,
                              height: 20.0,
                              child: GeneratedConnectwithusWidget5(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 788.0,
                              right: 281.0,
                              bottom: null,
                              width: null,
                              height: 23.0,
                              child: GeneratedContactWidget5(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 788.0,
                              right: 151.0,
                              bottom: null,
                              width: null,
                              height: 20.0,
                              child: Generated919015458338Widget5(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 56.0,
                              child: TransformHelper.translate(
                                  x: -147.50,
                                  y: 433.50,
                                  z: 0,
                                  child:
                                      GeneratedKooBlackIcon300x300Copy1Widget5()),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
