import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox77widget/generated/GeneratedIITmandi1Widget42.dart';
import 'package:flutterapp/untilapp/generatediphone11prox77widget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox77widget/generated/GeneratedBytesizemenuWidget33.dart';
import 'package:flutterapp/untilapp/generatediphone11prox77widget/generated/GeneratedFrame8Widget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox77widget/generated/GeneratedFrame29Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox77widget/generated/GeneratedRectangle1Widget42.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame iPhone 11 Pro / X - 77
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX77Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget42(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget42(),
              ),
              Positioned(
                left: 24.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: GeneratedBytesizemenuWidget33(),
              ),
              Positioned(
                left: 0.0,
                top: 151.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 661.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame8Widget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 91.0,
                top: 107.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 701.0,
                child: GeneratedRectangle38Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 694.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.84;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2693333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame29Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
