import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/Generated2IITMandiiHubHCIFoundationandITRACoLtdJapansignMoUWidge2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedIITMandiiHubHCIFoundationiHubWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedIITMandiCatalysthaslaunchedincubationprogramstodevelops2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedCarbonoverflowmenuverticalWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedAndIndiahavesignedawiderangingMoUtoharnesseachothersstr2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedIITmandi1Widget14.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedRectangle1Widget14.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedMoUWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/Generated4IITMandiiHubandHCIFoundationsignedMoUwithIITMandiCatal2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedIonchevronbackcircleWidget9.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedLinkhttpsdocsgooglecomspreadsheetsd1vp_ZtdmPoa2qDWwzcX02.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedMediaCoverageWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedBytesizemenuWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedToestablishstronglinkageswithnationalandinternationalor2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/Generated3IITMandiiHubandHCIFoundationsignwiderangingMoUwithNeur2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdsignMoU2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdIndiasf2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedIonchevronbackcircleWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedNeuroleap1Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedNeuroLeapWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedNeuroleapWidget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedHttpswwwiitmandiacinTIHHCIannoucementsphpWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedwwwihubiitmandiinWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedwwwrubiscapeioWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox68widget/generated/GeneratedITRACoLtdHeadquartersJapanTokyoRepresentativeDirectorKa2.dart';

/* Frame iPhone 11 Pro / X - 68
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX68Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1583.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1583.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 112.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.016;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget14(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 54.0,
                              child: TransformHelper.translate(
                                  x: -4.00,
                                  y: -711.50,
                                  z: 0,
                                  child: GeneratedIITmandi1Widget14()),
                            ),
                            Positioned(
                              left: 24.0,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -711.50,
                                  z: 0,
                                  child: GeneratedBytesizemenuWidget12()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -714.50,
                                  z: 0,
                                  child:
                                      GeneratedCarbonoverflowmenuverticalWidget12()),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 1434.0,
                              right: 19.0,
                              bottom: null,
                              width: null,
                              height: 72.0,
                              child:
                                  GeneratedIITMandiCatalysthaslaunchedincubationprogramstodevelops2(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 1381.0,
                              right: 50.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  Generated4IITMandiiHubandHCIFoundationsignedMoUwithIITMandiCatal2(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 1292.0,
                              right: 23.0,
                              bottom: null,
                              width: null,
                              height: 58.0,
                              child:
                                  GeneratedAndIndiahavesignedawiderangingMoUtoharnesseachothersstr2(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 1240.0,
                              right: 53.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  Generated3IITMandiiHubandHCIFoundationsignwiderangingMoUwithNeur2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 1145.0,
                              right: 26.0,
                              bottom: null,
                              width: null,
                              height: 86.0,
                              child:
                                  GeneratedITRACoLtdHeadquartersJapanTokyoRepresentativeDirectorKa2(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 923.0,
                              right: 62.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child:
                                  GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdsignMoU2(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 1098.0,
                              right: 53.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child:
                                  Generated2IITMandiiHubHCIFoundationandITRACoLtdJapansignMoUWidge2(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 848.0,
                              right: 28.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  GeneratedToestablishstronglinkageswithnationalandinternationalor2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 964.0,
                              right: 26.0,
                              bottom: null,
                              width: null,
                              height: 86.0,
                              child:
                                  GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdIndiasf2(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 794.0,
                              right: 162.0,
                              bottom: null,
                              width: null,
                              height: 34.0,
                              child: GeneratedMoUWidget2(),
                            ),
                            Positioned(
                              left: 239.0,
                              top: 963.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 55.0,
                              child: GeneratedwwwihubiitmandiinWidget2(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 1289.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 55.0,
                              child: GeneratedNeuroLeapWidget2(),
                            ),
                            Positioned(
                              left: 122.0,
                              top: 1293.0,
                              right: -62.0,
                              bottom: null,
                              width: null,
                              height: 52.0,
                              child:
                                  GeneratedIITMandiiHubHCIFoundationiHubWidget2(),
                            ),
                            Positioned(
                              left: 136.0,
                              top: 991.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 55.0,
                              child: GeneratedwwwrubiscapeioWidget2(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 711.0,
                              right: 18.0,
                              bottom: null,
                              width: null,
                              height: 19.0,
                              child:
                                  GeneratedHttpswwwiitmandiacinTIHHCIannoucementsphpWidget2(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 642.0,
                              right: 25.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  GeneratedLinkhttpsdocsgooglecomspreadsheetsd1vp_ZtdmPoa2qDWwzcX02(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 117.0,
                              right: 75.0,
                              bottom: null,
                              width: null,
                              height: 31.0,
                              child: GeneratedMediaCoverageWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 219.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 231.0,
                              child: GeneratedNeuroleap1Widget1(),
                            ),
                            Positioned(
                              left: 93.0,
                              top: 466.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedNeuroleapWidget1(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 327.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget8(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 272.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget9(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
