import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedArvindSharmaAssociateWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedBytesizemenuWidget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedImage11Widget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedFrame23Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/Generated360degreefieldviewCameraSuperComputerIOTDevices64Channe8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedAnkushPathaniaAssociateWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedAboutusWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedOculusRiftWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedFrame17Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedThematicareasWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedImage9Widget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedWeareoneofthe25TechnologyInnovationHubsTIHforhumancompu8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedMonishaBahugunaAssociateWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedEquipementsavailableWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedImage6Widget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedEquipmentComingSoonatiHubWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedRectangle1Widget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedFrame38Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedRectangle28Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedOurFacilitiesWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedIITmandi1Widget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedImage10Widget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedTIHTeamWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedImage8Widget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedNavdhaBhardwajAssociateWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedAnjanaPathaniaOfficeAttendantWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedHttpswwwiitmandiacinTIHHCIwhophpWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox37widget/generated/GeneratedTheprojectswillmainlyfocusondifferentaspectsofuserinter8.dart';

/* Frame iPhone 11 Pro / X - 37
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX37Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 9.0,
                top: 121.0,
                right: 8.999786376953125,
                bottom: null,
                width: null,
                height: 22.11505126953125,
                child: GeneratedFrame17Widget1(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: 0.0,
                width: 353.0,
                height: null,
                child: TransformHelper.translate(
                    x: 8.00,
                    y: 0.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double height =
                          constraints.maxHeight * 0.458128078817734;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: 0,
                            y: constraints.maxHeight * 0.27955665024630544,
                            z: 0,
                            child: Container(
                              height: height,
                              child: GeneratedFrame38Widget1(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.015999998728434245,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget8(),
              ),
              Positioned(
                left: 24.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: GeneratedBytesizemenuWidget7(),
              ),
              Positioned(
                left: 44.0,
                top: 1806.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 31.0,
                child: GeneratedEquipmentComingSoonatiHubWidget8(),
              ),
              Positioned(
                left: 46.0,
                top: 1737.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 31.0,
                child: GeneratedEquipementsavailableWidget8(),
              ),
              Positioned(
                left: 38.0,
                top: 1507.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 27.0,
                child: GeneratedMonishaBahugunaAssociateWidget8(),
              ),
              Positioned(
                left: 265.0,
                top: 1515.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 27.0,
                child: GeneratedArvindSharmaAssociateWidget8(),
              ),
              Positioned(
                left: 259.0,
                top: 1651.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 27.0,
                child: GeneratedNavdhaBhardwajAssociateWidget8(),
              ),
              Positioned(
                left: 31.0,
                top: 1647.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 27.0,
                child: GeneratedAnkushPathaniaAssociateWidget8(),
              ),
              Positioned(
                left: 161.0,
                top: 1580.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 27.0,
                child: GeneratedAnjanaPathaniaOfficeAttendantWidget8(),
              ),
              Positioned(
                left: 71.0,
                top: 988.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 37.0,
                child: GeneratedThematicareasWidget8(),
              ),
              Positioned(
                left: 111.0,
                top: 1325.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 37.0,
                child: GeneratedTIHTeamWidget8(),
              ),
              Positioned(
                left: 87.0,
                top: 1690.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 37.0,
                child: GeneratedOurFacilitiesWidget8(),
              ),
              Positioned(
                left: 27.0,
                top: 756.0,
                right: 33.0,
                bottom: null,
                width: null,
                height: 132.0,
                child:
                    GeneratedWeareoneofthe25TechnologyInnovationHubsTIHforhumancompu8(),
              ),
              Positioned(
                left: 27.0,
                top: 1041.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 245.0,
                child:
                    GeneratedTheprojectswillmainlyfocusondifferentaspectsofuserinter8(),
              ),
              Positioned(
                left: 27.0,
                top: 1373.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 26.0,
                child: GeneratedHttpswwwiitmandiacinTIHHCIwhophpWidget8(),
              ),
              Positioned(
                left: 41.0,
                top: 1762.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 21.0,
                child: GeneratedOculusRiftWidget8(),
              ),
              Positioned(
                left: 41.0,
                top: 1833.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child:
                    Generated360degreefieldviewCameraSuperComputerIOTDevices64Channe8(),
              ),
              Positioned(
                left: 123.0,
                top: 704.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 37.0,
                child: GeneratedAboutusWidget8(),
              ),
              Positioned(
                left: 35.0,
                top: 1409.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 91.0,
                child: GeneratedImage6Widget8(),
              ),
              Positioned(
                left: 255.0,
                top: 1417.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 95.0,
                child: GeneratedImage8Widget8(),
              ),
              Positioned(
                left: 27.0,
                top: 1550.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 84.0,
                child: GeneratedImage9Widget8(),
              ),
              Positioned(
                left: 272.0,
                top: 1559.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 89.0,
                child: GeneratedImage10Widget8(),
              ),
              Positioned(
                left: 162.0,
                top: 1474.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 100.0,
                child: GeneratedImage11Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 107.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 701.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7573333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24533333333333332,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle28Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 698.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.84;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2693333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame23Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
