import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox9widget/generated/GeneratedRectangle1Widget18.dart';
import 'package:flutterapp/untilapp/generatediphone11prox9widget/generated/GeneratedIITmandi1Widget18.dart';
import 'package:flutterapp/untilapp/generatediphone11prox9widget/generated/GeneratedBytesizemenuWidget15.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox9widget/generated/GeneratedStartupsWidget13.dart';
import 'package:flutterapp/untilapp/generatediphone11prox9widget/generated/GeneratedCarbonoverflowmenuverticalWidget15.dart';
import 'package:url_launcher/url_launcher.dart';

/* Frame iPhone 11 Pro / X - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget18(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget18(),
              ),
              Positioned(
                left: 24.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: GeneratedBytesizemenuWidget15(),
              ),
              Positioned(
                left: 0.0,
                top: 139.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 456.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedStartupsWidget13(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 52.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget15(),
              )
            ]),
      ),
    ));
  }
}
