import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedCarbonoverflowmenuverticalWidget23.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedRectangle1Widget28.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedTeamhttpsnmicpsgovinHomeICPSNMHOMEMGBWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedNMICPSWidget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedHomeWidget15.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedFeedbackWidget6.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedTeamWidget6.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedNationalMissiononInterdisciplinaryCyberPhysicalSystemsN1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedNMICPSWidget8.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedNMICPSisacomprehensiveMissionaimedatcompleteconvergence1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedMinistryofScienceTechnologyDeartmentofScienceTechnology1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedAkariconscirclechevronleftfillWidget6.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedImage12Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedIITmandi1Widget28.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedContactUsWidget6.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedFormorehttpsnmicpsgovinHomeICPSNMHOMEAboutusWidget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox50widget/generated/GeneratedAboutUsWidget6.dart';

/* Frame iPhone 11 Pro / X - 50
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX50Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 120.0,
                top: 139.0,
                right: 67.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedNMICPSWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0159999186197917;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016000001271565756,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget28(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget28(),
              ),
              Positioned(
                left: 24.0,
                top: 320.0,
                right: 36.0,
                bottom: null,
                width: null,
                height: 275.0,
                child:
                    GeneratedNMICPSisacomprehensiveMissionaimedatcompleteconvergence1(),
              ),
              Positioned(
                left: 30.0,
                top: 650.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 15.0,
                child:
                    GeneratedFormorehttpsnmicpsgovinHomeICPSNMHOMEAboutusWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 706.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 52.0,
                child: GeneratedTeamhttpsnmicpsgovinHomeICPSNMHOMEMGBWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 273.0,
                right: -60.0,
                bottom: null,
                width: null,
                height: 14.0,
                child:
                    GeneratedNationalMissiononInterdisciplinaryCyberPhysicalSystemsN1(),
              ),
              Positioned(
                left: 24.0,
                top: 284.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 26.0,
                child:
                    GeneratedMinistryofScienceTechnologyDeartmentofScienceTechnology1(),
              ),
              Positioned(
                left: 149.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 74.0,
                child: GeneratedImage12Widget1(),
              ),
              Positioned(
                left: null,
                top: 52.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget23(),
              ),
              Positioned(
                left: 0.0,
                top: 107.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 705.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6213333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle31Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 139.0,
                right: 160.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedAkariconscirclechevronleftfillWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 228.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.19466666666666665;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.20266666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedHomeWidget15(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 276.0000305175781,
                right: 0.0,
                bottom: null,
                width: null,
                height: 30.999969482421875,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2773333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16266666666666665,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedAboutUsWidget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 321.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18133333333333335,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedNMICPSWidget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 372.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 31.000030517578125,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3333333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16266666666666665,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedContactUsWidget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 421.99993896484375,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.00006103515625,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.30133333333333334;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18133333333333335,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFeedbackWidget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 464.00006103515625,
                right: 0.0,
                bottom: null,
                width: null,
                height: 33.99993896484375,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18133333333333335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23466666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedTeamWidget6(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
