import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedRectangle33Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedIITmandi1Widget40.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedAkariconscirclechevronleftfillWidget9.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedFabrandstwittersquareWidget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedBrandicoinstagramfilledWidget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedTrainingsWidget6.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedRectangle2Widget11.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedKooBlackIcon300x300Copy1Widget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedCarbonoverflowmenuverticalWidget31.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/Generated919015458338Widget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedHomeWidget18.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedWorkshopsWidget6.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedBrandicolinkedinrectWidget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedAboutUsWidget9.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedNMICPSWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedRectangle1Widget40.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedBrandicofacebookrectWidget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedConnectwithusWidget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedProgrammesWidget6.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedContactWidget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedTeamWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedSkillingWidget11.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedContactUsWidget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox73widget/generated/GeneratedFeedbackWidget10.dart';

/* Frame iPhone 11 Pro / X - 73
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX73Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget40(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 52.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget31(),
              ),
              Positioned(
                left: 0.0,
                top: 643.0,
                right: -6.0,
                bottom: null,
                width: null,
                height: 312.0,
                child: GeneratedRectangle2Widget11(),
              ),
              Positioned(
                left: 31.0,
                top: 289.0,
                right: 115.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedTrainingsWidget6(),
              ),
              Positioned(
                left: 31.0,
                top: 348.0,
                right: 115.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedProgrammesWidget6(),
              ),
              Positioned(
                left: 31.0,
                top: 219.0,
                right: 115.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedWorkshopsWidget6(),
              ),
              Positioned(
                left: 132.0,
                top: 151.0,
                right: 127.0,
                bottom: null,
                width: null,
                height: 40.0,
                child: GeneratedSkillingWidget11(),
              ),
              Positioned(
                left: 17.0,
                top: 673.0,
                right: 51.0,
                bottom: null,
                width: null,
                height: 110.0,
                child:
                    GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK10(),
              ),
              Positioned(
                left: 297.0,
                top: 885.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 55.0,
                child: GeneratedBrandicolinkedinrectWidget10(),
              ),
              Positioned(
                left: 224.0,
                top: 888.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 51.0,
                child: GeneratedBrandicofacebookrectWidget10(),
              ),
              Positioned(
                left: 156.0,
                top: 886.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 55.0,
                child: GeneratedBrandicoinstagramfilledWidget10(),
              ),
              Positioned(
                left: 84.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 60.0,
                child: GeneratedFabrandstwittersquareWidget10(),
              ),
              Positioned(
                left: 120.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 23.0,
                child: GeneratedConnectwithusWidget10(),
              ),
              Positioned(
                left: 24.0,
                top: 788.0,
                right: 287.0,
                bottom: null,
                width: null,
                height: 23.0,
                child: GeneratedContactWidget10(),
              ),
              Positioned(
                left: 107.0,
                top: 788.0,
                right: 150.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: Generated919015458338Widget10(),
              ),
              Positioned(
                left: 17.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 56.0,
                child: GeneratedKooBlackIcon300x300Copy1Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 107.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 705.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6213333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle33Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 140.0,
                right: 164.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedAkariconscirclechevronleftfillWidget9(),
              ),
              Positioned(
                left: 72.0,
                top: 229.0,
                right: 230.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: GeneratedHomeWidget18(),
              ),
              Positioned(
                left: 57.0,
                top: 277.0,
                right: 214.0,
                bottom: null,
                width: null,
                height: 25.0,
                child: GeneratedAboutUsWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 322.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedNMICPSWidget12(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 373.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 25.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3333333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.152,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedContactUsWidget9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 423.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.30133333333333334;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17066666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFeedbackWidget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 465.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18133333333333335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.224,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedTeamWidget12(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget40(),
              )
            ]),
      ),
    ));
  }
}
