import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedIonchevronbackcircleWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedCatalystWidget.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedCatalyst1Widget.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedRubiscapeWidget1.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedNeuroleap1Widget.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedRubiscape1Widget1.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedItra1Widget.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedIonchevronbackcircleWidget3.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedIonchevronbackcircleWidget6.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedITRAWidget.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedNeuroleapWidget.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedIonchevronbackcircleWidget4.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedIonchevronbackcircleWidget5.dart';
import 'package:flutterapp/untilapp/generatedframe11widget1/generated/GeneratedIonchevronbackcircleWidget1.dart';

/* Frame Frame 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame11Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 1766.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 482.0,
                      height: 351.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 276.0,
                              child: GeneratedRubiscape1Widget1(),
                            ),
                            Positioned(
                              left: 535.0,
                              top: 16.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 250.0,
                              child: GeneratedItra1Widget(),
                            ),
                            Positioned(
                              left: 1391.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 244.0,
                              child: GeneratedCatalyst1Widget(),
                            ),
                            Positioned(
                              left: 963.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 231.0,
                              child: GeneratedNeuroleap1Widget(),
                            ),
                            Positioned(
                              left: 1056.0,
                              top: 257.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedNeuroleapWidget(),
                            ),
                            Positioned(
                              left: 1484.0,
                              top: 269.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedCatalystWidget(),
                            ),
                            Positioned(
                              left: 608.0,
                              top: 269.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedITRAWidget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: TransformHelper.translate(
                                  x: 47.50,
                                  y: 150.50,
                                  z: 0,
                                  child: GeneratedRubiscapeWidget1()),
                            ),
                            Positioned(
                              left: 1338.0,
                              top: 113.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget1(),
                            ),
                            Positioned(
                              left: 915.0,
                              top: 163.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget2(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: -55.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: 24.50,
                                  z: 0,
                                  child:
                                      GeneratedIonchevronbackcircleWidget3()),
                            ),
                            Positioned(
                              left: 535.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget4(),
                            ),
                            Positioned(
                              left: 963.0,
                              top: 63.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget5(),
                            ),
                            Positioned(
                              left: 1386.0,
                              top: 133.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget6(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
