import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedEmailfmobasherah111gmailcomWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedRectangle1Widget32.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedContactWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedMrAvinashPunekarCEOIITMandiiHubandHCIFoundationWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedImage2Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedImage4Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedFabrandstwittersquareWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedImage3Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedChiefExecutiveOfficerWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedEmailmonishaihubiitmandiinWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedEmaildollychoudhary220gmailcomWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/Generated919015458338Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedEmailmfabasherahgmailcomWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedBytesizemenuWidget25.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedTeamWidget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedBrandicofacebookrectWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedFabasherahMalakWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedAssociatePROutreachWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedGiveusyourfeedbackhereWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedFrame28Widget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedImage7Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedEmailceoihubiitmandiinWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedKooBlackIcon300x300Copy1Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedBrandicoinstagramfilledWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedMobasherahFalakWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedDollyChoudharyWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedImage5Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedMonishaBahugunaWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedAppDevelopersWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedBrandicolinkedinrectWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedConnectwithusWidget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox43widget/generated/GeneratedIITmandi1Widget32.dart';

/* Frame iPhone 11 Pro / X - 43
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX43Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 593.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 341.0,
                child: GeneratedRectangle14Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.015999998728434245,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget32(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget32(),
              ),
              Positioned(
                left: 24.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: GeneratedBytesizemenuWidget25(),
              ),
              Positioned(
                left: -3.0,
                top: 1214.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 312.0,
                child: GeneratedRectangle2Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 217.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 338.0,
                child: GeneratedRectangle15Widget2(),
              ),
              Positioned(
                left: 23.0,
                top: 233.0,
                right: 68.0,
                bottom: null,
                width: null,
                height: 31.0,
                child: GeneratedChiefExecutiveOfficerWidget2(),
              ),
              Positioned(
                left: 23.0,
                top: 406.0,
                right: 68.0,
                bottom: null,
                width: null,
                height: 31.0,
                child: GeneratedAssociatePROutreachWidget2(),
              ),
              Positioned(
                left: 27.0,
                top: 598.0,
                right: 64.0,
                bottom: null,
                width: null,
                height: 31.0,
                child: GeneratedAppDevelopersWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 35.0,
                child:
                    GeneratedMrAvinashPunekarCEOIITMandiiHubandHCIFoundationWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 484.0,
                right: 33.0,
                bottom: null,
                width: null,
                height: 38.0,
                child: GeneratedEmailmonishaihubiitmandiinWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 466.0,
                right: 36.0,
                bottom: null,
                width: null,
                height: 35.0,
                child: GeneratedMonishaBahugunaWidget2(),
              ),
              Positioned(
                left: 26.0,
                top: 306.0,
                right: 34.0,
                bottom: null,
                width: null,
                height: 52.0,
                child: GeneratedEmailceoihubiitmandiinWidget2(),
              ),
              Positioned(
                left: 152.0,
                top: 152.0,
                right: 155.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedTeamWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 1008.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 37.0,
                child: GeneratedGiveusyourfeedbackhereWidget2(),
              ),
              Positioned(
                left: 17.0,
                top: 1233.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 60.0,
                child:
                    GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK2(),
              ),
              Positioned(
                left: 17.0,
                top: 836.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 84.0,
                child: GeneratedImage2Widget2(),
              ),
              Positioned(
                left: 141.750732421875,
                top: null,
                right: null,
                bottom: null,
                width: 77.27371978759766,
                height: 82.16021728515625,
                child: TransformHelper.translate(
                    x: 0.00, y: 357.08, z: 0, child: GeneratedImage3Widget2()),
              ),
              Positioned(
                left: null,
                top: 251.0,
                right: 33.0,
                bottom: null,
                width: 87.0,
                height: 97.0,
                child: GeneratedImage5Widget2(),
              ),
              Positioned(
                left: null,
                top: 422.0,
                right: 39.0,
                bottom: null,
                width: 71.0,
                height: 92.0,
                child: GeneratedImage7Widget2(),
              ),
              Positioned(
                left: 19.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 83.0,
                child: GeneratedImage4Widget2(),
              ),
              Positioned(
                left: 294.0,
                top: 1456.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 55.0,
                child: GeneratedBrandicolinkedinrectWidget2(),
              ),
              Positioned(
                left: 221.0,
                top: 1459.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 51.0,
                child: GeneratedBrandicofacebookrectWidget2(),
              ),
              Positioned(
                left: 153.0,
                top: 1457.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 55.0,
                child: GeneratedBrandicoinstagramfilledWidget2(),
              ),
              Positioned(
                left: 81.0,
                top: 1454.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 60.0,
                child: GeneratedFabrandstwittersquareWidget2(),
              ),
              Positioned(
                left: 117.0,
                top: 1423.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 23.0,
                child: GeneratedConnectwithusWidget2(),
              ),
              Positioned(
                left: 15.0,
                top: 1359.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 26.0,
                child: GeneratedContactWidget2(),
              ),
              Positioned(
                left: 93.0,
                top: 1359.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 23.0,
                child: Generated919015458338Widget2(),
              ),
              Positioned(
                left: 14.0,
                top: 1454.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 56.0,
                child: GeneratedKooBlackIcon300x300Copy1Widget2(),
              ),
              Positioned(
                left: 191.0,
                top: 672.0,
                right: -131.0,
                bottom: null,
                width: null,
                height: 35.0,
                child: GeneratedMobasherahFalakWidget2(),
              ),
              Positioned(
                left: 191.0,
                top: 766.0,
                right: -131.0,
                bottom: null,
                width: null,
                height: 35.0,
                child: GeneratedFabasherahMalakWidget2(),
              ),
              Positioned(
                left: 191.0,
                top: 859.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 35.0,
                child: GeneratedDollyChoudharyWidget2(),
              ),
              Positioned(
                left: 190.0,
                top: 705.0,
                right: 21.0,
                bottom: null,
                width: null,
                height: 52.0,
                child: GeneratedEmailfmobasherah111gmailcomWidget2(),
              ),
              Positioned(
                left: 188.0,
                top: 809.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child: GeneratedEmailmfabasherahgmailcomWidget2(),
              ),
              Positioned(
                left: 189.0,
                top: 885.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 52.0,
                child: GeneratedEmaildollychoudhary220gmailcomWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 107.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 701.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.757333251953125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24533333333333332,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle34Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 694.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.84;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2693333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame28Widget5(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
