import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedSubmitWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedTihiitmandiacinWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedCarbonoverflowmenuverticalWidget35.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedRectangle15Widget7.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedBrandicolinkedinrectWidget16.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedBrandicofacebookrectWidget16.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedFeedbackWidget13.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedWritetousWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedRectangle2Widget19.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedAboutUsWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedConnectwithusWidget16.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedKooBlackIcon300x300Copy1Widget16.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedFabrandstwittersquareWidget16.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedDropyourcommenthereWidget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedRectangle33Widget2.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedHomeWidget21.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedContactUsWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedFeedbackWidget14.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedNMICPSWidget15.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedBrandicoinstagramfilledWidget16.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/Generated919015458338Widget13.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedRectangle2Widget20.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedTeamWidget15.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedIITmandi1Widget46.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedAkariconscirclechevronleftfillWidget12.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedRectangle1Widget46.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK13.dart';
import 'package:flutterapp/untilapp/generatediphone11prox52widget/generated/GeneratedContactWidget13.dart';

/* Frame iPhone 11 Pro / X - 52
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX52Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.015999998728434245,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget46(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget46(),
              ),
              Positioned(
                left: null,
                top: 52.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget35(),
              ),
              Positioned(
                left: 0.0,
                top: 643.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 312.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle2Widget19(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 29.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedWritetousWidget4(),
              ),
              Positioned(
                left: 26.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 22.0,
                child: GeneratedDropyourcommenthereWidget1(),
              ),
              Positioned(
                left: 102.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 15.0,
                child: GeneratedTihiitmandiacinWidget4(),
              ),
              Positioned(
                left: 103.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 40.0,
                child: GeneratedFeedbackWidget13(),
              ),
              Positioned(
                left: 17.0,
                top: 673.0,
                right: 51.0,
                bottom: null,
                width: null,
                height: 110.0,
                child:
                    GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK13(),
              ),
              Positioned(
                left: 16.0,
                top: 297.0,
                right: 49.0,
                bottom: null,
                width: null,
                height: 157.0,
                child: GeneratedRectangle15Widget7(),
              ),
              Positioned(
                left: 228.0,
                top: 491.0,
                right: 25.0,
                bottom: null,
                width: null,
                height: 37.0,
                child: GeneratedSubmitWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 485.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 33.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 260.0;
                  final double scaleX = width <= 0 ? 0 : (width / 115.0);

                  final Widget child = GeneratedRectangle2Widget20();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(scaleX, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
                          0, 200.0 * scaleX, 485.0, 0, 1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 297.0,
                top: 885.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 55.0,
                child: GeneratedBrandicolinkedinrectWidget16(),
              ),
              Positioned(
                left: 224.0,
                top: 888.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 51.0,
                child: GeneratedBrandicofacebookrectWidget16(),
              ),
              Positioned(
                left: 156.0,
                top: 886.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 55.0,
                child: GeneratedBrandicoinstagramfilledWidget16(),
              ),
              Positioned(
                left: 84.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 60.0,
                child: GeneratedFabrandstwittersquareWidget16(),
              ),
              Positioned(
                left: 120.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 23.0,
                child: GeneratedConnectwithusWidget16(),
              ),
              Positioned(
                left: 18.0,
                top: 788.0,
                right: 281.0,
                bottom: null,
                width: null,
                height: 26.0,
                child: GeneratedContactWidget13(),
              ),
              Positioned(
                left: 96.0,
                top: 788.0,
                right: 138.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: Generated919015458338Widget13(),
              ),
              Positioned(
                left: 17.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 56.0,
                child: GeneratedKooBlackIcon300x300Copy1Widget16(),
              ),
              Positioned(
                left: 0.0,
                top: 106.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 706.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6213333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle33Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 136.0,
                right: 159.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedAkariconscirclechevronleftfillWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 225.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.19466666666666665;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.20533333333333334,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedHomeWidget21(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 273.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 25.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2773333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16533333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedAboutUsWidget12(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 318.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.184,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedNMICPSWidget15(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 369.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 25.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3333333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16533333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedContactUsWidget12(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 419.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.30133333333333334;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.184,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFeedbackWidget14(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 461.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18133333333333335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23733333333333334,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedTeamWidget15(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
