import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox54widget/generated/GeneratedBytesizemenuWidget27.dart';
import 'package:flutterapp/untilapp/generatediphone11prox54widget/generated/GeneratedFrame8Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox54widget/generated/GeneratedCarbonoverflowmenuverticalWidget27.dart';
import 'package:flutterapp/untilapp/generatediphone11prox54widget/generated/GeneratedIITmandi1Widget34.dart';
import 'package:flutterapp/untilapp/generatediphone11prox54widget/generated/GeneratedRectangle1Widget34.dart';

/* Frame iPhone 11 Pro / X - 54
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX54Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget34(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 57.0,
                height: 54.0,
                child: TransformHelper.translate(
                    x: -4.00,
                    y: -326.00,
                    z: 0,
                    child: GeneratedIITmandi1Widget34()),
              ),
              Positioned(
                left: 24.0,
                top: null,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -326.00,
                    z: 0,
                    child: GeneratedBytesizemenuWidget27()),
              ),
              Positioned(
                left: null,
                top: null,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -329.00,
                    z: 0,
                    child: GeneratedCarbonoverflowmenuverticalWidget27()),
              ),
              Positioned(
                left: 0.0,
                top: 151.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 661.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame8Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
