import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedAnubhav1Widget2.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedIonchevronbackcircleWidget43.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedPostDoc1Widget2.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedCallForProposalWidget1.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedIonchevronbackcircleWidget42.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedGM1Widget2.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedAnubhavFellowshipWidget2.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedRecruitmentWidget5.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedCFP1Widget1.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedIonchevronbackcircleWidget41.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedIonchevronbackcircleWidget44.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedIonchevronbackcircleWidget46.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedIonchevronbackcircleWidget45.dart';
import 'package:flutterapp/untilapp/generatedframe23widget3/generated/GeneratedPostDoctoralFellowshipWidget2.dart';

/* Frame Frame 23
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame23Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 1696.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 1696.0,
                      height: 550.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 1321.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 508.0,
                              child: GeneratedCFP1Widget1(),
                            ),
                            Positioned(
                              left: 868.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 199.0,
                              child: GeneratedAnubhav1Widget2(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 122.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 198.0,
                              child: GeneratedPostDoc1Widget2(),
                            ),
                            Positioned(
                              left: 175.0,
                              top: 358.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 31.0,
                              child: GeneratedRecruitmentWidget5(),
                            ),
                            Positioned(
                              left: 561.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedPostDoctoralFellowshipWidget2(),
                            ),
                            Positioned(
                              left: 998.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedAnubhavFellowshipWidget2(),
                            ),
                            Positioned(
                              left: 1464.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedCallForProposalWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 227.0,
                              child: GeneratedGM1Widget2(),
                            ),
                            Positioned(
                              left: 1325.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget41(),
                            ),
                            Positioned(
                              left: 865.0,
                              top: 201.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget42(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 188.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget43(),
                            ),
                            Positioned(
                              left: 400.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget44(),
                            ),
                            Positioned(
                              left: 816.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget45(),
                            ),
                            Positioned(
                              left: 1243.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget46(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
