import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedCatalyst1Widget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIonchevronbackcircleWidget28.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedCatalystWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedFrame28Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedITRAWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedNeuroLeapWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedwwwrubiscapeioWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedNeuroleapWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIITMandiiHubHCIFoundationiHubWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedwwwihubiitmandiinWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIonchevronbackcircleWidget29.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedLinkhttpsdocsgooglecomspreadsheetsd1vp_ZtdmPoa2qDWwzcX05.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedHttpswwwiitmandiacinTIHHCIannoucementsphpWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedBytesizemenuWidget14.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedAndIndiahavesignedawiderangingMoUtoharnesseachothersstr5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIonchevronbackcircleWidget24.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedRubiscapeWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIonchevronbackcircleWidget26.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedItra1Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIITmandi1Widget17.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdIndiasf5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIonchevronbackcircleWidget25.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/Generated4IITMandiiHubandHCIFoundationsignedMoUwithIITMandiCatal5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/Generated2IITMandiiHubHCIFoundationandITRACoLtdJapansignMoUWidge5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedITRACoLtdHeadquartersJapanTokyoRepresentativeDirectorKa5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIITMandiCatalysthaslaunchedincubationprogramstodevelops5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedMoUWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/Generated3IITMandiiHubandHCIFoundationsignwiderangingMoUwithNeur5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedRectangle1Widget17.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdsignMoU5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedRubiscape1Widget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedNeuroleap1Widget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedIonchevronbackcircleWidget27.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedMediaCoverageWidget5.dart';
import 'package:flutterapp/untilapp/generatediphone11prox40widget/generated/GeneratedToestablishstronglinkageswithnationalandinternationalor5.dart';

/* Frame iPhone 11 Pro / X - 40
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX40Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget17(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget17(),
              ),
              Positioned(
                left: 24.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: GeneratedBytesizemenuWidget14(),
              ),
              Positioned(
                left: 41.0,
                top: 1434.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedIITMandiCatalysthaslaunchedincubationprogramstodevelops5(),
              ),
              Positioned(
                left: 41.0,
                top: 1381.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child:
                    Generated4IITMandiiHubandHCIFoundationsignedMoUwithIITMandiCatal5(),
              ),
              Positioned(
                left: 37.0,
                top: 1292.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedAndIndiahavesignedawiderangingMoUtoharnesseachothersstr5(),
              ),
              Positioned(
                left: 38.0,
                top: 1240.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child:
                    Generated3IITMandiiHubandHCIFoundationsignwiderangingMoUwithNeur5(),
              ),
              Positioned(
                left: 34.0,
                top: 1145.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedITRACoLtdHeadquartersJapanTokyoRepresentativeDirectorKa5(),
              ),
              Positioned(
                left: 29.0,
                top: 923.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child:
                    GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdsignMoU5(),
              ),
              Positioned(
                left: 38.0,
                top: 1098.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child:
                    Generated2IITMandiiHubHCIFoundationandITRACoLtdJapansignMoUWidge5(),
              ),
              Positioned(
                left: 32.0,
                top: 848.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedToestablishstronglinkageswithnationalandinternationalor5(),
              ),
              Positioned(
                left: 34.0,
                top: 964.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdIndiasf5(),
              ),
              Positioned(
                left: 145.0,
                top: 794.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 40.0,
                child: GeneratedMoUWidget5(),
              ),
              Positioned(
                left: 239.0,
                top: 963.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 55.0,
                child: GeneratedwwwihubiitmandiinWidget5(),
              ),
              Positioned(
                left: 36.0,
                top: 1289.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 55.0,
                child: GeneratedNeuroLeapWidget5(),
              ),
              Positioned(
                left: 122.0,
                top: 1293.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child: GeneratedIITMandiiHubHCIFoundationiHubWidget5(),
              ),
              Positioned(
                left: 136.0,
                top: 991.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 55.0,
                child: GeneratedwwwrubiscapeioWidget5(),
              ),
              Positioned(
                left: 39.0,
                top: 711.0,
                right: 18.0,
                bottom: null,
                width: null,
                height: 55.0,
                child:
                    GeneratedHttpswwwiitmandiacinTIHHCIannoucementsphpWidget5(),
              ),
              Positioned(
                left: 35.0,
                top: 642.0,
                right: 25.0,
                bottom: null,
                width: null,
                height: 41.0,
                child:
                    GeneratedLinkhttpsdocsgooglecomspreadsheetsd1vp_ZtdmPoa2qDWwzcX05(),
              ),
              Positioned(
                left: 82.0,
                top: 123.0,
                right: 109.0,
                bottom: null,
                width: null,
                height: 31.0,
                child: GeneratedMediaCoverageWidget5(),
              ),
              Positioned(
                left: -108.0,
                top: 180.0,
                right: 1.0,
                bottom: null,
                width: null,
                height: 276.0,
                child: GeneratedRubiscape1Widget4(),
              ),
              Positioned(
                left: 427.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 250.0,
                child: GeneratedItra1Widget4(),
              ),
              Positioned(
                left: 1283.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 244.0,
                child: GeneratedCatalyst1Widget4(),
              ),
              Positioned(
                left: 855.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 231.0,
                child: GeneratedNeuroleap1Widget4(),
              ),
              Positioned(
                left: 948.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 60.0,
                child: GeneratedNeuroleapWidget4(),
              ),
              Positioned(
                left: 1376.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 60.0,
                child: GeneratedCatalystWidget4(),
              ),
              Positioned(
                left: 500.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 60.0,
                child: GeneratedITRAWidget4(),
              ),
              Positioned(
                left: 84.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 60.0,
                child: GeneratedRubiscapeWidget4(),
              ),
              Positioned(
                left: 1230.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget24(),
              ),
              Positioned(
                left: 807.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget25(),
              ),
              Positioned(
                left: 379.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget26(),
              ),
              Positioned(
                left: 427.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget27(),
              ),
              Positioned(
                left: 855.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget28(),
              ),
              Positioned(
                left: 1278.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget29(),
              ),
              Positioned(
                left: 0.0,
                top: 107.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 701.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7573333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24266666666666667,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle31Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 694.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.84;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2693333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame28Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
