import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedTeamWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedNMICPSWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedAboutUsWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedAboutusWidget10.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedHomeWidget13.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedCarbonoverflowmenuverticalWidget16.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedIITMandiiHubandHCIFoundationwaslaunchedonFebruary2420211.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedFeedbackWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedAkariconscirclechevronleftfillWidget4.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedIHubLogoShort1Widget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedIITmandi1Widget19.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedFormorehttpswwwiitmandiacinTIHHCIWidget1.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedRectangle1Widget19.dart';
import 'package:flutterapp/untilapp/generatediphone11prox49widget/generated/GeneratedContactUsWidget4.dart';

/* Frame iPhone 11 Pro / X - 49
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX49Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 123.0,
                top: 139.0,
                right: 129.0,
                bottom: null,
                width: null,
                height: 37.0,
                child: GeneratedAboutusWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 112.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.015999998728434245,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget19(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: 163.0,
                bottom: null,
                width: null,
                height: 54.0,
                child: GeneratedIITmandi1Widget19(),
              ),
              Positioned(
                left: 24.0,
                top: 312.0,
                right: 36.0,
                bottom: null,
                width: null,
                height: 80.0,
                child:
                    GeneratedIITMandiiHubandHCIFoundationwaslaunchedonFebruary2420211(),
              ),
              Positioned(
                left: 30.0,
                top: 437.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 15.0,
                child: GeneratedFormorehttpswwwiitmandiacinTIHHCIWidget1(),
              ),
              Positioned(
                left: null,
                top: 157.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 160.0,
                child: TransformHelper.translate(
                    x: -5.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedIHubLogoShort1Widget1()),
              ),
              Positioned(
                left: null,
                top: 52.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 107.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 705.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6213333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle30Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 139.0,
                right: 160.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedAkariconscirclechevronleftfillWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 228.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.19466666666666665;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.20266666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedHomeWidget13(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 276.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 31.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2773333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16266666666666665,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedAboutUsWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 321.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18133333333333335,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedNMICPSWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 372.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 31.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3333333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16266666666666665,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedContactUsWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 422.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.30133333333333334;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18133333333333335,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFeedbackWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 463.9999694824219,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.000030517578125,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18133333333333335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23466666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedTeamWidget4(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
