import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox10widget/generated/GeneratedRectangle1Widget27.dart';
import 'package:flutterapp/untilapp/generatediphone11prox10widget/generated/GeneratedIITmandi1Widget27.dart';
import 'package:flutterapp/untilapp/generatediphone11prox10widget/generated/GeneratedCarbonoverflowmenuverticalWidget22.dart';
import 'package:flutterapp/untilapp/generatediphone11prox10widget/generated/GeneratedBytesizemenuWidget22.dart';
import 'package:flutterapp/untilapp/generatediphone11prox10widget/generated/GeneratedFrame48Widget.dart';

/* Frame iPhone 11 Pro / X - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 955.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 955.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 112.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.016;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget27(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 155.0,
                              top: 53.0,
                              right: 163.0,
                              bottom: null,
                              width: null,
                              height: 54.0,
                              child: GeneratedIITmandi1Widget27(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 62.0,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: GeneratedBytesizemenuWidget22(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 127.0,
                              right: null,
                              bottom: null,
                              width: 409.0,
                              height: 593.0,
                              child: GeneratedFrame48Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: 52.0,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child:
                                  GeneratedCarbonoverflowmenuverticalWidget22(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
