import 'package:flutter/material.dart';
import 'package:flutterapp/untilapp/generatediphone11prox63widget/generated/GeneratedBytesizemenuWidget18.dart';
import 'package:flutterapp/untilapp/generatediphone11prox63widget/generated/GeneratedFrame17Widget3.dart';
import 'package:flutterapp/untilapp/generatediphone11prox63widget/generated/GeneratedCarbonoverflowmenuverticalWidget18.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/untilapp/generatediphone11prox63widget/generated/GeneratedRectangle1Widget22.dart';
import 'package:flutterapp/untilapp/generatediphone11prox63widget/generated/GeneratedIITmandi1Widget22.dart';

/* Frame iPhone 11 Pro / X - 63
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX63Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1463.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1463.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 112.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.016;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget22(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 54.0,
                              child: TransformHelper.translate(
                                  x: -4.00,
                                  y: -651.50,
                                  z: 0,
                                  child: GeneratedIITmandi1Widget22()),
                            ),
                            Positioned(
                              left: 24.0,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -651.50,
                                  z: 0,
                                  child: GeneratedBytesizemenuWidget18()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -654.50,
                                  z: 0,
                                  child:
                                      GeneratedCarbonoverflowmenuverticalWidget18()),
                            ),
                            Positioned(
                              left: -6.0,
                              top: 128.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 1335.0,
                              child: GeneratedFrame17Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
